### PR TITLE
Encourage collaboration

### PR DESCRIPTION
**Pull request by richardswain**
To encourage collaboration we should have a sentence in the footer that prompts users to make edits, add new pages etc.

### CODE REVIEW

**Comment by richardswain** [comment]
@willmot r/m (thoughts on the text needed) 

screen shot 2015-03-27 at 16 27 15


screen shot 2015-03-27 at 16 27 45

**Comment by willmot** [comment]
Nice!

**Comment by willmot** [comment]
@richardswain once merged & deployed could you setup the widget on live, the text above is 👍

**Comment by richardswain** [comment]
Widget & text now live.

**Comment by willmot** [comment]
\0/

**Pull request merged**
