### PR TITLE
Content Stubs

### PR DESCRIPTION
**Pull request by richardswain**
To encourage people to add new content to the handbook let's add the concept of content stubs, that is pages with a question as the title but with no content, questions that need an answer.

We can show those on the homepage under a separate widget. We'll probably want a category / tag to identify the pages that still require content.

### CODE REVIEW

**Comment by richardswain** [comment]
@willmot 1 plugin and 2 widgets added to the theme. 

Plugin to add categories to pages.

Widget to list pages for the content stubs category

Widget to list all pages and order by Post date and a duplicate of this in the footer but order by Modified date. 


Amended the footer text a little.

screen shot 2015-04-16 at 17 25 36

Still seems to be responsive to mobile with more posts etc.

screen shot 2015-04-16 at 17 34 55

**Comment by richardswain** [comment]
@willmot Comments?

Is a precursor to future changes discussed - issue to be added.

**Comment by willmot** [comment]
@richardswain looks solid, just one change; lets make the lists left-aligned instead of centre 👍

**Comment by willmot** [comment]
@richardswain in the first screenshot above the 2nd two widgets have the same content, is that expected?

**Comment by richardswain** [comment]
Kinda.

Here we have added a new "Page 1",
then added a "Content Stub Page 1",
then edited "Market Realist AWS Setup"

does that seem how you wanted the content displayed?

screen shot 2015-04-16 at 18 50 32

**Comment by richardswain** [comment]
Alignment?

screen shot 2015-04-16 at 18 57 40

**Comment by willmot** [comment]
@richardswain could you set those widgets up on the live site.

**Comment by richardswain** [comment]
@willmot Done - maybe cast your eye over the Page categories set up at some point

**Comment by willmot** [comment]
Thanks Richard, looks good!

**Pull request merged**
