### PR TITLE
Notifications for New Content

### PR DESCRIPTION
**Pull request by richardswain**
All users should receive notifications for new Handbook content and any changes.

### CODE REVIEW

**Comment by richardswain** [comment]
@scottbasgaard @willmot First stab, but is a WIP.

Its a shame Zapier doesn't integrate with Streams - this could have been a solution.

- Is "All users == "All Humans" ?
- Do you want no opt out?
- Currently the fn notifies on save regardless of content change (or not).
- Any ideas for presenting and checking the content delta

**Comment by willmot** [comment]
> Is "All users == "All Humans" ?

👍

> Do you want no opt out?

It would ideally use the same notifications toggle that other sites have on Hub

> Currently the fn notifies on save regardless of content change (or not).

Should only notify if it's changed, you should have access to old and new content at that point so can check if they're the same or not.

> Any ideas for presenting and checking the content delta

Could maybe use the revisions stuff... Not sure though

**Comment by rmccue** [comment]
> It would ideally use the same notifications toggle that other sites have on Hub

I'd be OK with extending Falcon to give notifications for page changes too. :)

**Comment by richardswain** [comment]
@willmot Is this still outstanding, since we could now use Slack Integrations?

**Comment by willmot** [comment]
Good call, we should pipe handbook updates to the general channel on Slack. May need to extend the plugin to support sending notifications for page changes.

**Comment by richardswain** [comment]
@willmot Added the Slack Integration, but updates & comments do not post to Slack. I've not created a post to double check that works tho.

**Comment by willmot** [comment]
Looks like new events can be hooked in with: http://gedex.web.id/wp-slack/

**Comment by richardswain** [comment]
Notifications via Slack https://github.com/humanmade/Human-Made-website/pull/776

**Pull request closed without merging**
